"""Robot Framework helper library for .

Auto-generated by bruno-to-robot converter.
Customize as needed for your test environment.
"""

import random
import time


def generate_00d_create_test_courier_body():
    """Generate request body for 00d - Create Test Courier.

    Auto-converted from Bruno before-request script.
    """
    import random
    import time

    first_names = ['Jan', 'Petr', 'Lucie', 'Eva', 'Tomas', 'Marie', 'David']
    last_names = ['Novak', 'Svoboda', 'Novotny', 'Dvorak', 'Cerny']
    streets = ['Narodni', 'Vinohradska', 'Dlouha', 'Masarykova', 'Vaclavske namesti']
    cities = ['Praha 1', 'Praha 2', 'Praha 3', 'Praha 4']
    domains = ['example.cz', 'mail.cz', 'seznam.cz']
    tags = ['bike', 'car', 'vip', 'express', 'fragile_ok']

    def random_item(arr):
        return random.choice(arr)

    def random_phone():
        return "+420" + str(random.randint(100000000, 999999999))

    def random_name():
        return f"{random_item(first_names)} {random_item(last_names)}"

    def random_address():
        return f"{random_item(streets)} {random.randint(1, 200)}, {random_item(cities)}"

    def random_coords(base_lat, base_lng, delta):
        lat = round(base_lat + (random.random() * 2 - 1) * delta, 6)
        lng = round(base_lng + (random.random() * 2 - 1) * delta, 6)
        return {"lat": lat, "lng": lng}

    timestamp = int(time.time())

    # Generate body based on detected patterns
    # TODO: Customize body structure based on actual request needs
    body = {
        "email": f"test{timestamp}@test.cz",
        "name": random_name(),
        "phone": random_phone(),
    }

    return body


def generate_10_create_order_body():
    """Generate request body for 10 - Create Order.

    Auto-converted from Bruno before-request script.
    """
    import random
    import time

    first_names = ['Jan', 'Petr', 'Lucie', 'Eva', 'Tomas', 'Marie', 'David']
    last_names = ['Novak', 'Svoboda', 'Novotny', 'Dvorak', 'Cerny']
    streets = ['Narodni', 'Vinohradska', 'Dlouha', 'Masarykova', 'Vaclavske namesti']
    cities = ['Praha 1', 'Praha 2', 'Praha 3', 'Praha 4']
    domains = ['example.cz', 'mail.cz', 'seznam.cz']
    tags = ['bike', 'car', 'vip', 'express', 'fragile_ok']

    def random_item(arr):
        return random.choice(arr)

    def random_phone():
        return "+420" + str(random.randint(100000000, 999999999))

    def random_name():
        return f"{random_item(first_names)} {random_item(last_names)}"

    def random_address():
        return f"{random_item(streets)} {random.randint(1, 200)}, {random_item(cities)}"

    def random_coords(base_lat, base_lng, delta):
        lat = round(base_lat + (random.random() * 2 - 1) * delta, 6)
        lng = round(base_lng + (random.random() * 2 - 1) * delta, 6)
        return {"lat": lat, "lng": lng}

    timestamp = int(time.time())

    # Generate body based on detected patterns
    # TODO: Customize body structure based on actual request needs
    body = {
        "email": f"test{timestamp}@test.cz",
        "name": random_name(),
        "phone": random_phone(),
    }

    return body


def generate_20_flow_create_order_body():
    """Generate request body for 20 - Flow Create Order.

    Auto-converted from Bruno before-request script.
    """
    import random
    import time

    first_names = ['Jan', 'Petr', 'Lucie', 'Eva', 'Tomas', 'Marie', 'David']
    last_names = ['Novak', 'Svoboda', 'Novotny', 'Dvorak', 'Cerny']
    streets = ['Narodni', 'Vinohradska', 'Dlouha', 'Masarykova', 'Vaclavske namesti']
    cities = ['Praha 1', 'Praha 2', 'Praha 3', 'Praha 4']
    domains = ['example.cz', 'mail.cz', 'seznam.cz']
    tags = ['bike', 'car', 'vip', 'express', 'fragile_ok']

    def random_item(arr):
        return random.choice(arr)

    def random_phone():
        return "+420" + str(random.randint(100000000, 999999999))

    def random_name():
        return f"{random_item(first_names)} {random_item(last_names)}"

    def random_address():
        return f"{random_item(streets)} {random.randint(1, 200)}, {random_item(cities)}"

    def random_coords(base_lat, base_lng, delta):
        lat = round(base_lat + (random.random() * 2 - 1) * delta, 6)
        lng = round(base_lng + (random.random() * 2 - 1) * delta, 6)
        return {"lat": lat, "lng": lng}

    timestamp = int(time.time())

    # Generate body based on detected patterns
    # TODO: Customize body structure based on actual request needs
    body = {
        "email": f"test{timestamp}@test.cz",
        "name": random_name(),
        "phone": random_phone(),
    }

    return body


