"""Robot Framework helper library for Users.

Auto-generated by bruno-to-robot converter.
Customize as needed for your test environment.
"""

import random
import time


def generate_create_random_user_body():
    """Generate request body for Create Random User.

    Auto-converted from Bruno before-request script.
    Original JS:
    const body = {};
body.email = 'user@test.cz';
req.setBody(JSON.stringify(body));
    """
    # TODO: Implement body generation
    body = {}
    return body


